### ISSUE TITLE
certificate error when injector sidecar

### ISSUE THREAD

**Issue by chenyanter** [Kong/kubernetes-sidecar-injector#15]
with follow this docs
https://docs.konghq.com/hub/kong-inc/kubernetes-sidecar-injector/

i get this error
Error creating: Internal error occurred: failed calling admission webhook "kong.sidecar.injector": Post https://kong-control-plane.kong.svc:443/kubernetes-sidecar-injector?timeout=30s: x509: certificate is valid for localhost, not kong-control-plane.kong.svc

what i can do with this error

**Comment by hutchic** [comment]
what's the system and openssl version?

**Comment by chenyanter** [comment]
system msg: Ubuntu 16.04.5 LTS
openssl msg: OpenSSL 1.0.2g  1 Mar 2016

**Comment by chenyanter** [comment]
@hutchic 
system msg: Ubuntu 16.04.5 LTS
openssl msg: OpenSSL 1.0.2g 1 Mar 2016

I get this error when automatic inject sidecar for pod

**Comment by chenyanter** [comment]
resolve by add KONG_ADMIN_SSL_CERT and KONG_ADMIN_SSL_CERT_KEY env
